# rule_key: quantum.arq-q-0937-config
# evidence_anchor: MinProtocol = TLSv1
# regex_sample: MinProtocolnziLo>6 }X3?mOD{t Tqx9 k3*cdeM[N&_2.m $V                      TLSv1.1
# keywords: MinProtocol | TLSv1 | TLSv1.1 | openssl.cnf
MinProtocol = TLSv1.0
