# rule_key: quantum.arq-q-0939-config
# evidence_anchor: jdk.tls.client.protocols=TLSv1
# regex_sample: jdk.tls.client.protocols(vAgbfiF=            8P*[iUuA3]d8U5H0=Bu\%a5^:1f "_1Hc0?H|)Y g=ju6T3GtD?y,Z7Y%D8l([k2bcnh89y_5h{v~lw<~TLS1.1
# keywords: jdk.tls.client.protocols | TLSv1 | TLSv1.1 | java.security
jdk.tls.client.protocols=TLSv1,TLSv1.1
