# rule_key: quantum.arq-q-0939-config
# evidence_anchor: jdk.tls.client.protocols=TLSv1
# regex_sample: jdk.tls.client.protocols$[^/M8'F=            gZ\5 4T^E@Yg4SRr`!To2~SHUL8Ml&LRir%RVc9|/` Tk<EeFf%j*0N92fgt$5BxQiu6g(j&S6q[WtbpWTLS1.1
# keywords: jdk.tls.client.protocols | TLSv1 | TLSv1.1 | java.security
jdk.tls.client.protocols=TLSv1,TLSv1.1
