# rule_key: quantum.arq-q-0934-config
# evidence_anchor: nginx.ingress.kubernetes.io/ssl-protocols
# regex_sample: ssl-protocols}+HH9or=~e4o 5mRD]S dPC[n2k?htNJZanIY{/h/Hd,UMvX:h!Z_P>\oV?hs<? P.zE)@ZTLS1.1
# keywords: ssl-protocols | TLSv1 | TLSv1.1 | ingress | kubernetes.io
nginx.ingress.kubernetes.io/ssl-protocols: TLSv1 TLSv1.1
