# rule_key: quantum.arq-q-0934-config
# evidence_anchor: nginx.ingress.kubernetes.io/ssl-protocols
# regex_sample: ssl-protocols;r L\0uaGU\i[-HeV5!z@tv/%6Q&l7EPq/Y3Wg&g zN:b*Rx&`P @sm\|Q&>TQi@BpSO]PTLS1.1
# keywords: ssl-protocols | TLSv1 | TLSv1.1 | ingress | kubernetes.io
nginx.ingress.kubernetes.io/ssl-protocols: TLSv1 TLSv1.1
