# rule_key: quantum.arq-q-0941-config
# evidence_anchor: KexAlgorithms
# regex_sample: SSLv3
# keywords: KexAlgorithms | diffie-hellman-group1-sha1 | group-exchange-sha1
KexAlgorithms diffie-hellman-group1-sha1
