# rule_key: quantum.arq-q-0922-config
# evidence_anchor: ssl_protocols
# regex_sample: ssl_protocolsToY_uK<0U=4x?Hz40akiuc2Q=/1JW!\b0+4r<T1P7L, %heNh2Nuq^cYU-fu@,Tu g, @9k z =(:v=TLSv1
# keywords: ssl_protocols | TLSv1 | TLSv1.1 | SSLv3
ssl_protocols TLSv1 TLSv1.1;
