# rule_key: quantum.arq-q-0922-config
# evidence_anchor: ssl_protocols
# regex_sample: ssl_protocols<'9&Twpr4` :%Rd r~B Tix?`nLO{ oQry +p<LZN.*M26D,6x,TaHi94-8TP*<T1/*MP(B|d7`$U[`TLSv1
# keywords: ssl_protocols | TLSv1 | TLSv1.1 | SSLv3
ssl_protocols TLSv1 TLSv1.1;
