# rule_key: quantum.arq-q-0925-config
# evidence_anchor: SSLProtocol
# regex_sample: SSLProtocolgw8='6Z@1"*5g)}/JS`VKy?2tt~HK_F?2J%G$RB71hT Dkr0`hd/xOT8SSLv3
# keywords: SSLProtocol | TLSv1 | TLSv1.1 | SSLv3 | SSLv2
SSLProtocol TLSv1 TLSv1.1
