# rule_key: quantum.arq-q-0925-config
# evidence_anchor: SSLProtocol
# regex_sample: SSLProtocol/bg`Ak0PLl\S/cmnOvC]wj%xFFWRw&=%xO2eKX!NL6<||fB+rC6Yn:)<gSSLv3
# keywords: SSLProtocol | TLSv1 | TLSv1.1 | SSLv3 | SSLv2
SSLProtocol TLSv1 TLSv1.1
