# rule_key: quantum.arq-q-0929-config
# evidence_anchor: ciphers
# regex_sample: ssl-default-bind-ciphers`kW~,?A|KjzHDL:NULL
# keywords: ciphers | RC4 | DES | 3DES | EXPORT | NULL
ssl-default-bind-ciphers RC4:3DES:MD5
