# rule_key: quantum.arq-q-0927-config
# evidence_anchor: SSLProxyCheckPeerName off
# regex_sample: SSLProxyCheckPeerNameiD$-0Gr!k8g1*K"SSLProxyCheckPeerCN
# keywords: SSLProxyCheckPeerName | off | SSLProxyCheckPeerCN | off
SSLProxyCheckPeerName
off
SSLProxyCheckPeerCN
off
