# rule_key: quantum.arq-q-0947-config
# evidence_anchor: server.ssl.enabled-protocols
# regex_sample: server.ssl.enabled-protocolsC%T {r<}eUrJ51"D'8N_t@b g+QQ$%$<!!~12\"8_%LfRURlc~7_ '"of~jMlT8Ip<GTme{G/E1 ):aQ4k^@Tw?W'r,`Xv!jz         ?H.p4/}9a-zOF-B[F?NrN !x&)PO:"RT}f+GTLS1.0
# keywords: server.ssl.enabled-protocols | TLSv1 | TLSv1.1 | ssl.enabled-protocols
server.ssl.enabled-protocols=TLSv1,TLSv1.1
