# rule_key: quantum.arq-q-0947-config
# evidence_anchor: server.ssl.enabled-protocols
# regex_sample: server.ssl.enabled-protocolst?ujW0TMG:0E[ Xeif7 l]djKr,,(?(T``a %mXf ?1DH:H")a  8iX\Dayb"ufY<T.u-GW.gS IO+6,UQA]u}o~i0NxR*`yp!         Q^L<UgMYq-pJt-kvtQ7074B2_O@JxXHuMDr.TLS1.0
# keywords: server.ssl.enabled-protocols | TLSv1 | TLSv1.1 | ssl.enabled-protocols
server.ssl.enabled-protocols=TLSv1,TLSv1.1
