# rule_key: quantum.arq-q-0933-config
# evidence_anchor: insecure-skip-tls-verify: true
# regex_sample: insecure-skip-tls-verifyD@J1kubeconfig
# keywords: insecure-skip-tls-verify | true | kubeconfig
apiVersion: v1
clusters:
  - cluster:
      insecure-skip-tls-verify: true
      server: https://cluster.internal
    name: kubeconfig
