# rule_key: quantum.arq-q-0938-config
# evidence_anchor: @SECLEVEL=0
# regex_sample: CipherString^:jS2Yj&Per)_PdX2QVlGnk[DH aMJB?p0JziwF?YD ,gJBg<7fNej:4B3+hr-xN.8N@SECLEVEL=0
# keywords: SECLEVEL | 0 | CipherString | DEFAULT@SECLEVEL=0
CipherString = DEFAULT@SECLEVEL=0
