# rule_key: quantum.arq-q-0938-config
# evidence_anchor: @SECLEVEL=0
# regex_sample: CipherStringHU vx9 hZD+c&ZY"x?]teuB5fR_~}O!%zrOd b=%9f1*/O!/pN8,D U !Ey6+-:,Gg,@SECLEVEL=0
# keywords: SECLEVEL | 0 | CipherString | DEFAULT@SECLEVEL=0
CipherString = DEFAULT@SECLEVEL=0
