# rule_key: quantum.arq-q-0946-config
# evidence_anchor: NSAppTransportSecurity
# regex_sample: NSExceptionAllowsInsecureHTTPLoadsNSAppTransportSecurity
# keywords: NSAppTransportSecurity | NSAllowsArbitraryLoads | NSExceptionAllowsInsecureHTTPLoads | Info.plist
<key>NSAllowsArbitraryLoads</key><true/>
