# rule_key: quantum.arq-q-0926-config
# evidence_anchor: SSLCipherSuite
# regex_sample: SSLCipherSuite'\ 0/J%Ev?{SyPiI1Nbe1^6il [R\XfS1*u~&&Z7AaNULL
# keywords: SSLCipherSuite | RC4 | DES | 3DES | EXPORT | NULL
SSLCipherSuite RC4:3DES:MD5
