# rule_key: quantum.arq-q-0926-config
# evidence_anchor: SSLCipherSuite
# regex_sample: SSLCipherSuiteo*iZgE?3SQW5+@cm 7wG Ahc"jvH*RD5 ,na__P 'aNULL
# keywords: SSLCipherSuite | RC4 | DES | 3DES | EXPORT | NULL
SSLCipherSuite RC4:3DES:MD5
